
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 14;
  public static final int OS = 13;
  public static final int PLUS = 8;
  public static final int CM = 18;
  public static final int STAR = 10;
  public static final int CB = 12;
  public static final int OB = 11;
  public static final int EOF = 0;
  public static final int DIV = 9;
  public static final int SUM_WD = 17;
  public static final int SEP = 2;
  public static final int CMP_WD = 16;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int TOKEN3 = 5;
  public static final int TOKEN2 = 4;
  public static final int TOKEN1 = 3;
  public static final int UINT = 19;
  public static final int SC = 6;
  public static final int INS_WD = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOKEN1",
  "TOKEN2",
  "TOKEN3",
  "SC",
  "MINUS",
  "PLUS",
  "DIV",
  "STAR",
  "OB",
  "CB",
  "OS",
  "CS",
  "INS_WD",
  "CMP_WD",
  "SUM_WD",
  "CM",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("CS");
		TT[13]=new String("OS");
		TT[8]=new String("PLUS");
		TT[18]=new String("CM");
		TT[10]=new String("STAR");
		TT[12]=new String("CB");
		TT[11]=new String("OB");
		TT[0]=new String("EOF");
		TT[9]=new String("DIV");
		TT[17]=new String("SUM_WD");
		TT[2]=new String("SEP");
		TT[16]=new String("CMP_WD");
		TT[7]=new String("MINUS");
		TT[1]=new String("error");
		TT[5]=new String("TOKEN3");
		TT[4]=new String("TOKEN2");
		TT[3]=new String("TOKEN1");
		TT[19]=new String("UINT");
		TT[6]=new String("SC");
		TT[15]=new String("INS_WD");
	}
public String getTT(int i){return TT[i];}
}

